version: '3.8'

services:
  app:
    container_name: backend-server
    build: .
    ports:
      - '1026:3000'
    depends_on:
      - mongo

  mongo:
    container_name: database
    image: mongo
    ports:
      - '27017:27017'

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
