import { ALL_PERMISSIONS } from './permissions'

export const CONSTANTS = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    USER: 'USER',
    ADMIN: 'ADMIN',
    MAINTAINER: 'MAINTAINER',
  },
  PERMISSIONS: ALL_PERMISSIONS,
}

export const RESPONSE = {
  USER_CREATED : 'USER CREATED SUCCESSFULLY',
  USER_UPDATED : 'USER UPDATED SUCCESSFULLY',
  USER_DELETED : 'USER DELETED SUCCESSFULLY',
  USER_NOT_FOUND : 'USER NOT FOUND',
  USER_ALREADY_EXISTS : 'USER ALREADY EXISTS',
  USER_DOES_NOT_EXISTS : 'USER DOES NOT EXISTS',
  USER_INVALID_CREDENTIALS : 'INVALID CREDENTIALS',
  BAD_REQUEST : 'BAD REQUEST',
  INVALID_OTP : 'INVALID OTP',
  USER_TOKEN_EXPIRED : 'TOKEN EXPIRED',
  USER_TOKEN_INVALID : 'TOKEN INVALID',
  USER_TOKEN_MISSING : 'TOKEN MISSING',
  ACCESS_DENIED : 'ACCESS DENIED',
  WRONG_DOMAIN : 'WRONG DOMAIN',
  USER_WITH_EMAIL_ALREADY_EXISTS: 'USER WITH EMAIL OR USERNAME ALREADY EXISTS',
  USER_REGISTERED_SUCCESSFULLY: 'USER REGISTERED SUCCESSFULLY',
  USER_LOGGED_IN_SUCCESSFULLY: 'USER LOGGED IN SUCCESSFULLY',
  USER_LOGGED_OUT_SUCCESSFULLY: 'USER LOGGED OUT SUCCESSFULLY',
  ACCOUNT_NOT_VERIFIED: 'YOUR ACCOUNT IS NOT VERIFIED',
  UNAUTHORIZED: "UNAUTHORIZED ACCESS",
  TOKEN_REFRESHED_SUCCESSFULLY: 'TOKEN REFRESHED SUCCESSFULLY',
  USER_ALREADY_VERIFIED: 'USER ALREADY VERIFIED',
  OTP_EXPIRED: 'OTP EXPIRED',
  EMAIL_VERIFIED: "EMAIL VERIFIED SUCCESSFULLY",
  OTP_RESEND: 'OTP RESEND SUCCESSFULLY',
}